//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLySieuXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongMuaBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDongMuaBan()
        {
            this.HoaDonBanHangs = new HashSet<HoaDonBanHang>();
        }
    
        public string MaHopDong { get; set; }
        public string MaKhachHang { get; set; }
        public string MaXe { get; set; }
        public Nullable<System.DateTime> NgayLapHopDong { get; set; }
        public string DieuKhoanHopDong { get; set; }
        public Nullable<decimal> TongGiaTriHopDong { get; set; }
        public string MaNhanVienPheDuyet { get; set; }
        public string TrangThaiHopDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBanHang> HoaDonBanHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
