//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLySieuXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        public string MaPhieuNhap { get; set; }
        public string MaXe { get; set; }
        public string MaNhaCungCap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
