//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLySieuXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatKho
    {
        public string MaPhieuXuat { get; set; }
        public string MaXe { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<decimal> GiaXuat { get; set; }
        public string MaNhanVienKiemTra { get; set; }
        public string TrangThaiDonHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
